### ISSUE TITLE
Xvisor not booting on RISC V core synthesized on FPGA 

### ISSUE THREAD

**Issue by FrancoAuri1996** [xvisor/xvisor#164] opened 2023-07-12 14:11 UTC
Hi Anup, I'm trying to run Xvisor on a Rocket risc v core synthesized on the Digilent nexys a7-100t board FPGA but the boot process is stuck right after openSBI boot sequence. 
At first, I thought that it was related with the serial driver, so i made it and then added to Xvisor code, but after that i had the same problem.
Using Vitis debugger i discovered that openSBI jumps to a wrong address in the cpu_entry.S file of Xvisor, in particular to the address 0x100001c4 (line 244 in cpu_entry.S). I show some screens down below.
![Last instruction before cpu_entry s](https://github.com/xvisor/xvisor/assets/131985763/c7b5e0fe-175b-4c2c-9f37-f3ead1586404)
![First instruction reached in cpu_entry s](https://github.com/xvisor/xvisor/assets/131985763/8d9d1c1e-cd92-4131-b82c-162b1e69633d)
I compiled the project with the 12.1.0 version of the GCC risc v compiler.
Could you suggest me what to do in order to solve this problem?

**Comment by avpatel** [comment] 2023-07-12 16:10
Xvisor jumping to 0x100001c4 address after `csrw CSR_SATP, a0` instruction using a instruction fetch trap is expected behavior because Xvisor is linked at 0x10000000 address so after enabling MMU we try to run from link-time address.

**Comment by FrancoAuri1996** [comment] 2023-07-13 08:40
Ok, so the MMU enabling process starts before entering in the cpu_entry.S? I ask you this beacause contuinuig the execution i got trapped in a loop caused by a memory fault error. I show you in the next screens.
![Schermata del 2023-07-13 10-37-04](https://github.com/xvisor/xvisor/assets/131985763/652b32de-bf36-444e-8480-be5576b96ffd)
![Schermata del 2023-07-13 10-37-16](https://github.com/xvisor/xvisor/assets/131985763/f8744ac8-8125-40eb-8f10-d9c8eeab6a44)
![Schermata del 2023-07-13 10-37-33](https://github.com/xvisor/xvisor/assets/131985763/ef13a22c-ca69-481c-a62f-9524bce3014e)

**Comment by avpatel** [comment] 2023-07-13 13:08
I double checked in my environment with QEMU. The `a0` register is not getting set to `-1`

**Comment by avpatel** [comment] 2023-07-13 13:11
What is the state of GPRs, stvec, scause, and stval when you see the first trap after enabling MMU (i.e. at `REG_S tp, ...` instruction)

**Comment by FrancoAuri1996** [comment] 2023-07-13 13:39
Here you can see the registers values.
![Schermata del 2023-07-13 15-36-50](https://github.com/xvisor/xvisor/assets/131985763/a1554965-ac36-4f77-954c-e2d8fbee2a0b)
![Schermata del 2023-07-13 15-35-59](https://github.com/xvisor/xvisor/assets/131985763/06f8b661-915b-46d0-ac0d-3953ef781979)

**Comment by avpatel** [comment] 2023-07-13 13:53
Are you willing to do a screen sharing session ? 
I can create a google meeting.

**Comment by FrancoAuri1996** [comment] 2023-07-13 13:55
Yes sure, this is my email: francesco.auriemma237@gmail.com

**Comment by FrancoAuri1996** [comment] 2023-07-13 13:59
Ok thank you Anup, see you later

**Comment by FrancoAuri1996** [comment] 2023-07-17 14:14
I managed to print the value of "riscv_xlen" variable, it has a strange value, so i'll try to skip the branch and and see if then the code goes on, i leave a screenshot.
![Schermata del 2023-07-17 16-02-17](https://github.com/xvisor/xvisor/assets/131985763/3031be74-1575-44bf-ab90-792b233b08b4)

**Comment by FrancoAuri1996** [comment] 2023-07-17 15:55
ok i think i solved the previous problem, simply reassigned 0 to riscv_xlen variable and the code went on. 
After that there is an exception in the arch_board_early_init() function, i show in the next screens the output
![Schermata del 2023-07-17 17-38-19](https://github.com/xvisor/xvisor/assets/131985763/d7e7cac5-2bdb-4795-8562-004e96e135cc)
![Schermata del 2023-07-17 17-38-45](https://github.com/xvisor/xvisor/assets/131985763/5693cd48-11ec-4650-b065-7e55d68704f5)
![Schermata del 2023-07-17 17-38-56](https://github.com/xvisor/xvisor/assets/131985763/d1845370-49e8-432a-952c-bbd0a52b8d02)
![Schermata del 2023-07-17 17-40-56](https://github.com/xvisor/xvisor/assets/131985763/65f75aa7-b924-4bff-9ccf-252a1d1ea5fb)
![Schermata del 2023-07-17 17-45-57](https://github.com/xvisor/xvisor/assets/131985763/45f967f2-e257-4a0b-a34d-791fe080dcf1)

**Comment by avpatel** [comment] 2023-07-17 16:02
I think you will hit more such global variable uninitialised cases.

**Comment by FrancoAuri1996** [comment] 2023-07-18 08:24
Mmh ok, so maybe it is a compilation problem?  Furthermore, i'm booting using openSBI + Xvisor vmm.bin file + DTB, should i try booting Xvisor using also U-boot and Xvisor disk.img file?

**Comment by FrancoAuri1996** [comment] 2023-07-18 10:20
Ok, so maybe that portion of code is not executing for an unknown reason, i'll investigate about that and i'll report as soon as possible the results here in the issue. Furthermore, here is the registers values when the exception i found yesterday starts. I guess it is a load page fault.
![Schermata del 2023-07-18 12-16-41](https://github.com/xvisor/xvisor/assets/131985763/0d84a0a3-26b9-4560-a31b-e6630d22ce45)

**Comment by avpatel** [comment] 2023-07-18 10:57
Looks like the `clk_root_list` global variable is not initialized correctly. I think you should fix the global variable issue and most of these issues will go away.

**Comment by FrancoAuri1996** [comment] 2023-07-18 13:35
Ok i modified a little bit the cpu_entry.S file to force the code to execute the BSS istructions, and here we can see what happens
![Schermata del 2023-07-18 15-17-31](https://github.com/xvisor/xvisor/assets/131985763/a6520711-7420-4c09-85f8-40b894fea840)
![Schermata del 2023-07-18 15-18-17](https://github.com/xvisor/xvisor/assets/131985763/36465f42-8d8f-48d1-a64f-b4efae3ff0e5)
![Schermata del 2023-07-18 15-19-27](https://github.com/xvisor/xvisor/assets/131985763/16b3e8cc-9160-4d35-ae33-2472c0e38a76)
When we reach         REG_S	zero, (a0)    instruction, line 150,  there is an exception and the code jumps again to    la  a6, __cpu_init  instruction, line 247, whose address is in the stvec register. 
Searching in the memory, the address 0x8028B000, pointed from a0 register, has unknown values and i guess that's why there is the exception.
Do you think this is something that can be solved modifing Xvisor configuration flags as we did last time?

**Comment by FrancoAuri1996** [comment] 2023-07-26 14:30
Hi Anup, i manged to go on with the execution but now i'm stuck on this csr_write(CSR_HIDELEG, HIDELEG_DEFAULT); instruction. This line triggers an exception whose cause is "illegal instruction", and i think that it's related with the fact that my risc v core doesn't have the H-extension. Is this idea correct? Does Xvisor need to run on a core whith H-extension enabled to work properly on risc-v?
![Schermata del 2023-07-26 15-21-37](https://github.com/xvisor/xvisor/assets/131985763/9e294634-bf1f-4f40-9c32-69cfd9a06b10)

**Comment by FrancoAuri96** [comment] 2023-10-17 09:39
Hi Anup, i managed to add h extension to my design and, after resolving some other little problems, i think the boot of Xvisor is complete. Unfortunately, now i have a problem with the scheduler: in particular, when calling the arch_vcpu_preempt_orphan() function, the code enters in the cpu_proc.S file and there is an exception when the REG_S zero, (zero) instruction is executed.
As i red from your patch notes, the arch_vcpu_preempt_orphan() function implementation is platform dependent, and since i'm running Xvisor on the rocket chip synthetized on the nexys a7-100t, so not on qemu, i think that this is the problem.
Could you suggest any solution?

**Comment by avpatel** [comment] 2023-10-17 12:15
The arch_preempt_orphan_vcpu() should work on Rocket chip because it simply tries to write to a virtual address 0x0 which is not mapped in HS-mode page table hence generates a fault which in-turn prempts the VCPU.

**Comment by FrancoAuri96** [comment] 2023-10-17 15:57
Ok, so it is an expected behavior.
I followed the flow of execution in vitis and the code arrives to line 107 where rc variable is set to VMM_EFAIL and then an error message is printed.
![Schermata del 2023-10-17 17-42-44](https://github.com/xvisor/xvisor/assets/108072751/976b1a44-9864-43bc-91f9-eb63c706c8c0)
Since this code in particular was made when the h extension were not implemented, at least this is what i uderstood from the patch notes, maybe the first if branch should be executed, now that we have h-extension, and so also the vmm_scheduler_preempt_orphan(regs) function should be executed?

**Comment by FrancoAuri96** [comment] 2023-10-26 12:42
Hi Anup, after some experiments i think i managed to solve the last problem commentig line 96. 
At first i tried to solve the problem removing the negation operator, but it didn't work completely because sometimes the if branch was activated and other times no.
Now the scheduling for orphan CPU seems to work fine and i think the hypervisor is running.
At this point i have a problem with the serial driver, it seems that no interruption arrives from my keyboard. I expected this problem because i just adapted the zynq driver present in Xvisor to work with the nexys a7-100t in approximate way.
Anyway, i'd like to ask you how to boot Xvisor .bin file, device tree and ramdisk all together on my board. The example for risk v is only available for qemu, so i followed the guide to boot Xvisor on the zcu102 with u-boot. 
In my case i built OpenSBI thath lunch u-boot and than, manually from u-boot terminal, i'm trying to boot vmm.bin + dtb + ramdisk.
It seems like the code is loaded inside an illegal memory region.
If you want to do a call on meets as we did in july i would be very happy to do that, beacuse i think i'm really close to make Xvisor work on my core synthetized on the 100t.

**Closed** 2023-11-02 14:02 UTC
